nameOverride: byteboard-service

image:
  repository: krosengr4/byteboard-service
  tag: latest

service:
  port: 8080
  nodePort: 30080

replicas: 1

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"

config:
  dbHost: "localhost"
  dbPort: "5432"
  dbUser: "postgres"
  dbName: "byteboard_db"
  port: "8080"
