nameOverride: byteboard-service

image:
  repository: krosengr4/byteboard-service
  tag: latest

service:
  port: 8080
  nodePort: 30080

replicas: 1

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"

config:
  postgresHost: "localhost"
  postgresPort: "5432"
  postgresDB: "byteboard_db"
  postgresUser: "postgres"
  postgressSSLMode: "disable"
  port: "8080"
